name: Law assist DACN-242 production CI

on:
  push:
    branches: [ "main", "master" ]

jobs:

  docker-build-push:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3.10.0
      id: buildx

    - name: Cache Docker image layers
      uses: actions/cache@v4.2.3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-key: |
          ${{ runner.os }}-buildx-
          
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.15.0
      id: docker_build
      with:
        platforms: linux/amd64,linux/arm64
        context: ./
        file: ./Dockerfile
        push: true
        build-args: |
          "NEXT_PUBLIC_API_HOST=${{ vars.NEXT_PUBLIC_API_HOST }}",
          "REMOTE_PROTOCOL=${{ vars.REMOTE_PROTOCOL }}",
          "REMOTE_HOSTNAME=${{ vars.REMOTE_HOSTNAME }}",
          "REMOTE_PHOTO_MOCK_DATA=${{ vars.REMOTE_PHOTO_MOCK_DATA }}",
          "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}",
          "NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}",
          "NODE_TLS_REJECT_UNAUTHORIZED=0"
        tags: ${{ secrets.DOCKER_USERNAME }}/law-assist-dacn242-prod
        cache-to: type=local,dest=./tmp/.buildx-cache
        cache-from: type=local,src=./tmp/.buildx-cache

    - name: Verify CI/CD pipeline
      run: echo ${{ steps.docker_build.outputs.digest }}
